LanguageLeap/urls.py
from django.urls import path

from . import views

app_name = "leap"
urlpatterns = [
    path("catalog/", views.catalog, name="catalog"),
    path("register/", views.user_registration, name = "register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("text/<int:text_id>/", views.text, name = "text"),
    path("upload_text", views.upload_text, name = "upload_text"),
    path("translate_word/<int:text_id>/<int:paragraph>/<int:word_number>", views.translate_word.as_view(), name="translate_word"),
    path("learn/", views.learn_page, name = 'learn'),
    path("saved_word_update/<int:id>/<int:is_correct>",views.saved_word_update,name="saved_word_update"),
    path("saves", views.my_profile, name="my_profile"),
    path("delete_text/<int:text_id>/", views.delete_text, name="delete_text"),
    path("update_text_status/<int:text_id>/<slug:button_name>", views.update_text_status, name="update_text_status"),
    path("json/catalog/", views.json_catalog, name="json_catalog"),
    path("api/learn", views.api_learn_page.as_view(), name="api_learn"),
    path("api/login", views.api_login, name="api_login"),
    path("api/profile", views.api_profile.as_view(), name="api_profile"),
    path("api/text/<int:text_id>/", views.api_text.as_view(), name= "api_text"),
    path("api/update_text_status/<int:text_id>/<int:status>", views.update_text_status_api.as_view(),
         name="api_update_text_status"),
    path("api/new_text", views.api_new_text.as_view(), name= "api_new_text"),
    path("api/register", views.api_register_user.as_view(), name="api_register"),
    path("get_heatmap_data/<slug:user_name>/", views.get_heatmap_data, name="get_heatmap_data"),
    path("")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("LanguageLeap.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LanguageLeap/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.contrib.auth.models import User


class Language(models.Model):
    name = models.CharField(max_length=128)
    code = models.CharField(max_length=32)
    image = models.ImageField(upload_to="languages/")
    voice_name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class LanguageLevel(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class Text(models.Model):
    name = models.CharField(max_length=256)
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    language_level = models.ForeignKey(LanguageLevel, blank=True, on_delete=models.PROTECT)
    text = models.TextField()
    audio = models.FileField(upload_to="textAudio/", blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)
    image = models.ImageField(upload_to="textImage/", blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)

    @property
    def split_text(self):
        txt = str(self.text)
        paragraph = list(txt.split("\n"))
        ans = list()
        for p in paragraph:
            ans.append(list(p.split(" ")))
        return ans

    @property
    def save_count(self):
        return self.savedtext_set.count()


    def get_paragraph(self, paragraph_number):


        return self.split_text[paragraph_number]


    def get_word(self, paragraph_number, word_number):

        return self.get_paragraph(paragraph_number)[word_number]

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Word(models.Model):
    word = models.CharField(max_length=256)
    audio = models.FileField(upload_to="wordAudio/")

    translation = models.CharField(max_length=256)
    definition = models.TextField()
    synonyms = ArrayField(models.CharField(max_length=256), null=True)
    antonyms = ArrayField(models.CharField(max_length=256), null=True)

    text = models.ForeignKey(Text, on_delete=models.PROTECT)
    paragraph = models.IntegerField()
    word_in_paragraph = models.IntegerField()

    def __str__(self):
        return self.word


class KnowledgeDegree(models.Model):
    duration = models.DurationField()


class SavedWord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.PROTECT)
    knowledge_degree = models.ForeignKey(KnowledgeDegree, on_delete=models.PROTECT)
    next_rep = models.DateTimeField()
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.word


class SavedTextStatus(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name + " " + str(self.id)


class SavedText(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.ForeignKey(Text, on_delete=models.CASCADE)
    save_date = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(SavedTextStatus, on_delete=models.PROTECT)

    def __str__(self):
        return self.text.name


class ActivityTracker(models.Model):
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    counter = models.IntegerField(default=1)


    def plus_one(self):
        self.counter += 1
        self.save()


class KnownWord(models.Model):
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.PROTECT)


class KnownWord(models.Model):
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.PROTECT)

LanguageLeap/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Text


class RegistrationForm(forms.Form):
    username = forms.CharField(label="Имя пользователя", max_length=100)
    email = forms.CharField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль")

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Пользователь с данным именем уже существует")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с данным email уже существует")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError("Пароли должны совпадать")

        return cleaned_data


class TextForm(ModelForm):
    class Meta:
        model = Text
        fields = ["name", "text", "language", "language_level", "public", "image", "audio"]

LanguageLeap/views.py
import json
import string

from django.core.exceptions import PermissionDenied
from django.db.models import Count, OuterRef, Subquery
from django.db.models.functions import Coalesce
from rest_framework import status
from rest_framework.permissions import IsAuthenticated, AllowAny
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector
from django.core import serializers
from django.core.serializers import serialize
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login, logout
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView

from mysite import settings
from .models import Text, LanguageLevel, Language, Profile, Word, SavedWord, SavedText, ActivityTracker, KnownWord
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from .forms import RegistrationForm, TextForm
from gtts import gTTS
from datetime import datetime
import os
from PyMultiDictionary import MultiDictionary
from translate import Translator
from nltk.stem import WordNetLemmatizer
from django.utils import timezone
from datetime import timedelta
from google import genai
from pydantic import BaseModel, Field
from typing import List, Optional


# Create your views here.
def catalog(request):
    texts = Text.objects.filter(public=True)
    if request.user.is_authenticated:
        texts = texts.filter(language_id=request.user.profile.language_id)
    language_levels = LanguageLevel.objects.all()
    form_values = {"searchField": "",
                   "minLevel": 1,
                   "maxLevel": 6}
    if request.GET:
        form_values["searchField"] = request.GET["searchField"]
        form_values["minLevel"] = int(request.GET["minLevel"])
        form_values["maxLevel"] = int(request.GET["maxLevel"])
        if form_values['searchField']:
            texts = texts.filter(text__icontains=form_values['searchField']) | texts.filter(
                name__icontains=form_values['searchField'])
        texts = texts.filter(language_level_id__gte=form_values["minLevel"],
                             language_level_id__lte=form_values["maxLevel"])

    return render(request, "LanguageLeap/catalog.html", {
        "texts": texts,
        "language_levels": language_levels,
        "form_values": form_values,
    })


@csrf_protect
def user_registration(request):
    languages = Language.objects.all()
    form = RegistrationForm()

    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            language = request.POST["language"]
            user = User.objects.create_user(username, email, password)
            user.save()
            profile = Profile(language_id=language, user=user)
            profile.save()
            login(request, user)
            return redirect("leap:my_profile")

    return render(request, "LanguageLeap/registration.html", {
        "languages": languages,
        "form": form,
    })


@csrf_protect
def user_login(request):
    errors = []
    if request.POST:
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("leap:my_profile")
        else:
            errors.append("Неправильное имя или пароль")
    return render(request, "LanguageLeap/login.html", {"errors": errors})


def user_logout(request):
    logout(request)
    return redirect("leap:login")


def filter_words(user, text_id):

    saved_words = user.savedword_set.filter(word__text_id=text_id).order_by("word__word")

    return saved_words


@login_required
def text(request, text_id):
    text = get_object_or_404(Text, pk=text_id)
    words = filter_words(request.user, text_id)
    try:
        saved_text = SavedText.objects.get(user = request.user, text= text)
        text_status = saved_text.status.id
    except:
        text_status = 0

    return render(request, "LanguageLeap/text.html", {"text": text, "words": words, "text_status":text_status})


class api_text(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, text_id):
        text = get_object_or_404(Text, pk=text_id)
        try:
            saved_text = SavedText.objects.get(user = request.user, text= text)
            text_status = saved_text.status.id
        except:
            text_status = 0
        return JsonResponse({"text": {
            "id": text.id, "name": text.name, "text": text.text, "audio": text.audio.url
        }, "text_status": text_status})


@csrf_protect
@login_required
def upload_text(request):
    form = TextForm()
    if request.method == "POST":
        form = TextForm(request.POST)
        if form.is_valid():
            new_text = Text()
            new_text.user = request.user
            new_text.name = form.cleaned_data["name"]
            new_text.text = form.cleaned_data["text"]
            new_text.language = form.cleaned_data["language"]
            new_text.language_level = form.cleaned_data["language_level"]
            new_text.public = form.cleaned_data["public"]
            if form.cleaned_data["image"]:
                new_text.image = form.cleaned_data["image"]
            else:
                new_text.image.name = "textImage/book.jpg"
            if form.cleaned_data["audio"]:
                new_text.audio = form.cleaned_data["audio"]
            else:
                new_text.save()
                audio_dir = os.path.join(settings.MEDIA_ROOT, 'textAudio')
                os.makedirs(audio_dir, exist_ok=True)
                audio_filename = f"{new_text.id}.mp3"
                audio_path = os.path.join(audio_dir, audio_filename)
                audio = gTTS(text=form.cleaned_data["text"], lang=new_text.language.code)
                audio.save(audio_path)
                new_text.audio.name = os.path.join('textAudio', audio_filename)
            new_text.save()
            return redirect("leap:text", text_id=new_text.pk)
    return render(request, "LanguageLeap/upload_text.html", {"form": form})


class translate_word(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, text_id, paragraph, word_number):
        try:
            word_object = Word.objects.get(text_id=text_id, paragraph=paragraph, word_in_paragraph=word_number)
        except Word.DoesNotExist:
            text = get_object_or_404(Text, pk=text_id)


            try:
                word = text.get_word(paragraph,word_number)
            except:
                raise Http404()
            print("new word:", word)
            word_object = Word(text_id=text_id, paragraph=paragraph, word_in_paragraph=word_number)




            client = genai.Client()

            class Responce(BaseModel):
                word: str = Field(description="Исходное слово в начальной форме или выражение")
                translation: str = Field(description="перевод слова или выражения на русский язык")
                definition: str = Field(description="объяснение заначения слова на исходном языке")
                synonyms: Optional[List[str]] = Field(description="список из трех синонимов слова")
                antonyms: Optional[List[str]] = Field(description="список из трех антонимов слова")

            prompt = f"""
            ты являешься учителем иностранного языка. твоя задача объяснить ученику значение слова {word} в контексте (слово {word} - {word_number+1} слово в абзаце): 
            {" ".join(text.get_paragraph(paragraph))}
            в ответе выведи: 
            1.исходное слово, если слово является частью фразеологизма или другого неразрывного выражения напиши все выражение, если слово находится не в начальной форме приведи его в начальную форму
            2. перевод слова или выражения из первого пункта на русский язык с учетом контекста
            3. определение(объяснение) слова или выражение из первого пункта на исходном языке, понятное ученику
            4. если можешь приведи список из 3 синонимов к слову или выражению из 1 пункта(синоним также может быть словом или выражением)
            5. если можешь приведи список из 3 антонимов к слову или выражению из 1 пункта(антоним также может быть словом или выражением)
            """

            for attempt in range(3):
                response = client.models.generate_content(
                    model="gemini-3-flash-preview",
                    contents=prompt,
                    config={
                        "response_mime_type": "application/json",
                        "response_json_schema": Responce.model_json_schema(),
                    },
                )
                try:
                    response = Responce.model_validate_json(response.text)
                    break
                except Exception as e:
                    print(f"Ошибка валидации: {e}. Повторная попытка...")
                    if attempt == 2:
                        raise





            word_object.word = response.word
            word_object.translation = response.translation
            word_object.definition = response.definition
            word_object.synonyms = response.synonyms or None
            word_object.antonyms = response.antonyms or None

            audio_dir = os.path.join(settings.MEDIA_ROOT, 'wordAudio')
            os.makedirs(audio_dir, exist_ok=True)

LanguageLeap/templates/LanguageLeap/footer.html
<footer style="width: 100%; background-color: #f4f4f4; padding: 20px 0; margin: 0; font-family: 'Arial', sans-serif;">
    <div style="max-width: 1200px; margin: 0 auto; text-align: center;">
        <p style="color: #333; margin: 0;">&copy; 2025 Language Leap.</p>
        <ul style="list-style: none; padding: 0; display: flex; justify-content: center;">

        </ul>
    </div>
</footer>

LanguageLeap/templates/LanguageLeap/header.html
<header style="background-color: #fff; border-bottom: 1px solid #eaeaea; width: 100%; padding: 0; margin: 0; font-family: 'Arial', sans-serif;">
    <div style="display: flex; justify-content: space-between; align-items: center; width: 100%; padding: 10px 0px;">
        <h1 style="color: #2c3e50; margin: 10px 10px;">Language Leap</h1>
        <nav>
            <ul style="display: flex; list-style: none; padding: 0; margin: 0;">

                <li style="margin-right: 30px;">
                    <a href="{%url 'leap:learn'%}" style="text-decoration: none; color: #3498db;">Учить слова</a>
                </li>
                <li style="margin-right: 30px;">
                    <a href="{%url 'leap:catalog'%}" style="text-decoration: none; color: #3498db;">Библиотека</a>
                </li>
                <li style="margin-right: 30px;">
                    <a href="{%url 'leap:my_profile'%}" style="text-decoration: none; color: #3498db;">Сохранённое</a>
                </li>
            </ul>
        </nav>
    </div>
</header>

LanguageLeap/templates/LanguageLeap/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Личный кабинет</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <script src="https://d3js.org/d3.v7.min.js"></script>
<!-- v6 is also supported -->
<script src="https://d3js.org/d3.v6.min.js"></script>
<script src="https://unpkg.com/cal-heatmap/dist/cal-heatmap.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/cal-heatmap/dist/cal-heatmap.css">
    <script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/cal-heatmap/dist/plugins/Tooltip.min.js"></script>
    <style>

        .main-content {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
            color: #333;
        }
        a{
        text-decoration:none;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #2c3e50;
            margin-bottom: 20px;
        }

        .user-info {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 30px;
        }

        .username {
            font-size: 1.5em;
            color: #2c3e50;
        }

        .logout-button, .add-text-button {
            background-color: #3498db;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .logout-button:hover, .add-text-button:hover {
            background-color: #2980b9;
        }

        .section {
            width: 100%;
            background-color: #fdfdfd;
            border: 1px solid #eee;
            border-radius: 8px;
            margin-bottom: 20px;
            padding: 15px;
        }

        .section-header {
            background-color: #3498db;
            color: #fff;
            padding: 10px;
            text-align: left;
            font-size: 1.2em;
            font-weight: bold;
            cursor: pointer;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .text-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: 20px;
            padding-top: 15px;
            display: none;
        }

        .text-list.expanded {
            display: grid;
        }

        .text-item {
            position: relative;
        }

        .text-block {
            background-color: #fdfdfd;
            border: 1px solid #eee;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
        }

        .text-block img {
            width: 100%;
            height: 150px;
            object-fit: cover;
        }

        .text-content {
            padding: 15px;
        }

        .text-content h3 {
            margin-top: 0;
            margin-bottom: 10px;
            color: #2c3e50;
        }

        .text-details {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .language-level {
            background-color: #e8f0fe;
            color: #3498db;
            padding: 5px 10px;
            border-radius: 4px;
            font-size: 0.9em;
            font-weight: bold;
        }

        .delete-text-button {
            background-color: #e74c3c;
            color: #fff;
            border: none;
            padding: 5px 10px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 0.8em;
        }

        .delete-text-button:hover {
            background-color: #c0392b;
        }
    </style>
</head>

<body>
{% include 'LanguageLeap/header.html' %}
<div class="main-content">
    <div class="container">
        <div class="user-info">
            <h1 class="username">Имя Пользователя: {{user.username}}</h1>


            <div>

                <a href="{% url 'leap:logout'%}" class="add-text-button">Выйти</a>
                <a href="{% url 'leap:upload_text'%}" class="add-text-button">Добавить текст</a>
            </div>
        </div>

        <div class="section">
            <div class="section-header" data-section="addedTexts">Мои тексты <i class="fas fa-chevron-down"></i></div>
            <div class="text-list" id="addedTexts">
                {%for text in my_texts%}

                <div class="text-item">
                    <div class="text-block">
                        <a href="{%url 'leap:text' text.id %}"><img src="{{text.image.url}}" alt="{{text.name}}"></a>
                        <div class="text-content">
                            <a href="{%url 'leap:text' text.id %}"><h3>{{text.name}}</h3></a>
                            <div class="text-details">
                                <span class="language-level">{{text.language_level.name}}</span>
                                <button class="delete-text-button" data-text-name="{{text.name}}" data-text-id="{{text.id}}">Удалить</button>
                            </div>
                        </div>
                        </div>
                    </div>

                {%endfor%}


            </div>
        </div>

        <div class="section">
            <div class="section-header" data-section="readTexts">Прочитанные тексты <i class="fas fa-chevron-down"></i></div>
            <div class="text-list" id="readTexts">
                {%for text in completed_texts%}

                <div class="text-item">
                    <div class="text-block">
                        <a href="{%url 'leap:text' text.id %}"><img src="{{text.image.url}}" alt="{{text.name}}"></a>
                        <div class="text-content">
                            <a href="{%url 'leap:text' text.id %}"><h3>{{text.name}}</h3></a>
                            <div class="text-details">
                                <span class="language-level">{{text.language_level.name}}</span>

                            </div>
                        </div>
                        </div>
                    </div>

                {%endfor%}


            </div>
        </div>

        <div class="section">
            <div class="section-header" data-section="readingTexts">Сейчас читаю <i class="fas fa-chevron-down"></i></div>
            <div class="text-list" id="readingTexts">
                {%for text in current_texts%}

                <div class="text-item">
                    <div class="text-block">
                        <a href="{%url 'leap:text' text.id %}"><img src="{{text.image.url}}" alt="{{text.name}}"></a>
                        <div class="text-content">
                            <a href="{%url 'leap:text' text.id %}"><h3>{{text.name}}</h3></a>
                            <div class="text-details">
                                <span class="language-level">{{text.language_level.name}}</span>

                            </div>
                        </div>
                        </div>
                    </div>

                {%endfor%}

            </div>
        </div>

        <div class="section">
            <div class="section-header" data-section="laterTexts">Буду читать <i class="fas fa-chevron-down"></i></div>
            <div class="text-list" id="laterTexts">
                {%for text in future_texts%}

                <div class="text-item">
                    <div class="text-block">
                        <a href="{%url 'leap:text' text.id %}"><img src="{{text.image.url}}" alt="{{text.name}}"></a>
                        <div class="text-content">
                            <a href="{%url 'leap:text' text.id %}"><h3>{{text.name}}</h3></a>
                            <div class="text-details">
                                <span class="language-level">{{text.language_level.name}}</span>

                            </div>
                        </div>
                        </div>
                    </div>

                {%endfor%}

            </div>
        </div>
    <div id="cal-heatmap"></div>
    </div>
</div>
{% include 'LanguageLeap/footer.html' %}
    <script>




    const cal = new CalHeatmap();



    cal.paint({

    date:{locale: 'ru',timezone: 'Europe/Moscow', highlight: [

      new Date(), // Highlight today
    ],},

    domain: { type: 'month' },

    subDomain: { type: 'day',radius: 2},
    start: new Date(2026, 0, 1),
    data: { type:"json",
            source: "{% url 'leap:get_heatmap_data' user.username%}",
            x: d => d.creation_date,
            y: d => d.cards_done+d.saved_words,
            defaultValue: 0,},

    scale: {
        color: {

          scheme: 'Blues',
          type: 'linear',
          domain: [0, 30],
        },
  },
  }, [[
      Tooltip,
      {
        text: function (creation_date ,value) {
          return (
            (creation_date ? `${new Date(creation_date).toLocaleDateString()} Повторено или добавлено слов: ${value}
    `:"Нет данных")
          );
        },
      },
    ]]);







        document.addEventListener('DOMContentLoaded', function () {
            const sectionHeaders = document.querySelectorAll('.section-header');

            sectionHeaders.forEach(header => {
                header.addEventListener('click', function () {
                    const sectionId = this.getAttribute('data-section');
                    const textList = document.getElementById(sectionId);
                    const isExpanded = textList.classList.contains('expanded');

                    textList.classList.toggle('expanded', !isExpanded);
                });
            });

            const deleteButtons = document.querySelectorAll('.delete-text-button');
            deleteButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const textName = this.getAttribute('data-text-name');
                    const textId = this.getAttribute("data-text-id")
                    conf = confirm(`Удалите текст: ${textName}`);
                    if (conf){
                        window.location.assign(`/delete_text/${textId}`)

                    }
                });
            });
        });
    </script>
</body>
</html>